// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export class LXCContainer extends pulumi.CustomResource {
    /**
     * Get an existing LXCContainer resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LXCContainerState, opts?: pulumi.CustomResourceOptions): LXCContainer {
        return new LXCContainer(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'proxmox:index/lXCContainer:LXCContainer';

    /**
     * Returns true if the given object is an instance of LXCContainer.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LXCContainer {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LXCContainer.__pulumiType;
    }

    public readonly arch!: pulumi.Output<string | undefined>;
    public readonly bwlimit!: pulumi.Output<number | undefined>;
    public readonly clone!: pulumi.Output<string | undefined>;
    public readonly cloneStorage!: pulumi.Output<string | undefined>;
    public readonly cmode!: pulumi.Output<string | undefined>;
    public readonly console!: pulumi.Output<boolean | undefined>;
    public readonly cores!: pulumi.Output<number | undefined>;
    public readonly cpulimit!: pulumi.Output<number | undefined>;
    public readonly cpuunits!: pulumi.Output<number | undefined>;
    public readonly description!: pulumi.Output<string | undefined>;
    public readonly features!: pulumi.Output<outputs.LXCContainerFeatures | undefined>;
    public readonly force!: pulumi.Output<boolean | undefined>;
    public readonly full!: pulumi.Output<boolean | undefined>;
    public readonly hagroup!: pulumi.Output<string | undefined>;
    public readonly hastate!: pulumi.Output<string | undefined>;
    public readonly hookscript!: pulumi.Output<string | undefined>;
    public readonly hostname!: pulumi.Output<string | undefined>;
    public readonly ignoreUnpackErrors!: pulumi.Output<boolean | undefined>;
    public readonly lock!: pulumi.Output<string | undefined>;
    public readonly memory!: pulumi.Output<number | undefined>;
    public readonly mountpoints!: pulumi.Output<outputs.LXCContainerMountpoint[] | undefined>;
    public readonly nameserver!: pulumi.Output<string | undefined>;
    public readonly networks!: pulumi.Output<outputs.LXCContainerNetwork[] | undefined>;
    public readonly onboot!: pulumi.Output<boolean | undefined>;
    public readonly ostemplate!: pulumi.Output<string | undefined>;
    public readonly ostype!: pulumi.Output<string>;
    public readonly password!: pulumi.Output<string | undefined>;
    public readonly pool!: pulumi.Output<string | undefined>;
    public readonly protection!: pulumi.Output<boolean | undefined>;
    public readonly restore!: pulumi.Output<boolean | undefined>;
    public readonly rootfs!: pulumi.Output<outputs.LXCContainerRootfs | undefined>;
    public readonly searchdomain!: pulumi.Output<string | undefined>;
    public readonly sshPublicKeys!: pulumi.Output<string | undefined>;
    public readonly start!: pulumi.Output<boolean | undefined>;
    public readonly startup!: pulumi.Output<string | undefined>;
    public readonly swap!: pulumi.Output<number | undefined>;
    public readonly tags!: pulumi.Output<string | undefined>;
    public readonly targetNode!: pulumi.Output<string>;
    public readonly template!: pulumi.Output<boolean | undefined>;
    public readonly tty!: pulumi.Output<number | undefined>;
    public readonly unique!: pulumi.Output<boolean | undefined>;
    public readonly unprivileged!: pulumi.Output<boolean | undefined>;
    public /*out*/ readonly unuseds!: pulumi.Output<string[]>;
    public readonly vmid!: pulumi.Output<number | undefined>;

    /**
     * Create a LXCContainer resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LXCContainerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LXCContainerArgs | LXCContainerState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as LXCContainerState | undefined;
            resourceInputs["arch"] = state ? state.arch : undefined;
            resourceInputs["bwlimit"] = state ? state.bwlimit : undefined;
            resourceInputs["clone"] = state ? state.clone : undefined;
            resourceInputs["cloneStorage"] = state ? state.cloneStorage : undefined;
            resourceInputs["cmode"] = state ? state.cmode : undefined;
            resourceInputs["console"] = state ? state.console : undefined;
            resourceInputs["cores"] = state ? state.cores : undefined;
            resourceInputs["cpulimit"] = state ? state.cpulimit : undefined;
            resourceInputs["cpuunits"] = state ? state.cpuunits : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["features"] = state ? state.features : undefined;
            resourceInputs["force"] = state ? state.force : undefined;
            resourceInputs["full"] = state ? state.full : undefined;
            resourceInputs["hagroup"] = state ? state.hagroup : undefined;
            resourceInputs["hastate"] = state ? state.hastate : undefined;
            resourceInputs["hookscript"] = state ? state.hookscript : undefined;
            resourceInputs["hostname"] = state ? state.hostname : undefined;
            resourceInputs["ignoreUnpackErrors"] = state ? state.ignoreUnpackErrors : undefined;
            resourceInputs["lock"] = state ? state.lock : undefined;
            resourceInputs["memory"] = state ? state.memory : undefined;
            resourceInputs["mountpoints"] = state ? state.mountpoints : undefined;
            resourceInputs["nameserver"] = state ? state.nameserver : undefined;
            resourceInputs["networks"] = state ? state.networks : undefined;
            resourceInputs["onboot"] = state ? state.onboot : undefined;
            resourceInputs["ostemplate"] = state ? state.ostemplate : undefined;
            resourceInputs["ostype"] = state ? state.ostype : undefined;
            resourceInputs["password"] = state ? state.password : undefined;
            resourceInputs["pool"] = state ? state.pool : undefined;
            resourceInputs["protection"] = state ? state.protection : undefined;
            resourceInputs["restore"] = state ? state.restore : undefined;
            resourceInputs["rootfs"] = state ? state.rootfs : undefined;
            resourceInputs["searchdomain"] = state ? state.searchdomain : undefined;
            resourceInputs["sshPublicKeys"] = state ? state.sshPublicKeys : undefined;
            resourceInputs["start"] = state ? state.start : undefined;
            resourceInputs["startup"] = state ? state.startup : undefined;
            resourceInputs["swap"] = state ? state.swap : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
            resourceInputs["targetNode"] = state ? state.targetNode : undefined;
            resourceInputs["template"] = state ? state.template : undefined;
            resourceInputs["tty"] = state ? state.tty : undefined;
            resourceInputs["unique"] = state ? state.unique : undefined;
            resourceInputs["unprivileged"] = state ? state.unprivileged : undefined;
            resourceInputs["unuseds"] = state ? state.unuseds : undefined;
            resourceInputs["vmid"] = state ? state.vmid : undefined;
        } else {
            const args = argsOrState as LXCContainerArgs | undefined;
            if ((!args || args.targetNode === undefined) && !opts.urn) {
                throw new Error("Missing required property 'targetNode'");
            }
            resourceInputs["arch"] = args ? args.arch : undefined;
            resourceInputs["bwlimit"] = args ? args.bwlimit : undefined;
            resourceInputs["clone"] = args ? args.clone : undefined;
            resourceInputs["cloneStorage"] = args ? args.cloneStorage : undefined;
            resourceInputs["cmode"] = args ? args.cmode : undefined;
            resourceInputs["console"] = args ? args.console : undefined;
            resourceInputs["cores"] = args ? args.cores : undefined;
            resourceInputs["cpulimit"] = args ? args.cpulimit : undefined;
            resourceInputs["cpuunits"] = args ? args.cpuunits : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["features"] = args ? args.features : undefined;
            resourceInputs["force"] = args ? args.force : undefined;
            resourceInputs["full"] = args ? args.full : undefined;
            resourceInputs["hagroup"] = args ? args.hagroup : undefined;
            resourceInputs["hastate"] = args ? args.hastate : undefined;
            resourceInputs["hookscript"] = args ? args.hookscript : undefined;
            resourceInputs["hostname"] = args ? args.hostname : undefined;
            resourceInputs["ignoreUnpackErrors"] = args ? args.ignoreUnpackErrors : undefined;
            resourceInputs["lock"] = args ? args.lock : undefined;
            resourceInputs["memory"] = args ? args.memory : undefined;
            resourceInputs["mountpoints"] = args ? args.mountpoints : undefined;
            resourceInputs["nameserver"] = args ? args.nameserver : undefined;
            resourceInputs["networks"] = args ? args.networks : undefined;
            resourceInputs["onboot"] = args ? args.onboot : undefined;
            resourceInputs["ostemplate"] = args ? args.ostemplate : undefined;
            resourceInputs["ostype"] = args ? args.ostype : undefined;
            resourceInputs["password"] = args ? args.password : undefined;
            resourceInputs["pool"] = args ? args.pool : undefined;
            resourceInputs["protection"] = args ? args.protection : undefined;
            resourceInputs["restore"] = args ? args.restore : undefined;
            resourceInputs["rootfs"] = args ? args.rootfs : undefined;
            resourceInputs["searchdomain"] = args ? args.searchdomain : undefined;
            resourceInputs["sshPublicKeys"] = args ? args.sshPublicKeys : undefined;
            resourceInputs["start"] = args ? args.start : undefined;
            resourceInputs["startup"] = args ? args.startup : undefined;
            resourceInputs["swap"] = args ? args.swap : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["targetNode"] = args ? args.targetNode : undefined;
            resourceInputs["template"] = args ? args.template : undefined;
            resourceInputs["tty"] = args ? args.tty : undefined;
            resourceInputs["unique"] = args ? args.unique : undefined;
            resourceInputs["unprivileged"] = args ? args.unprivileged : undefined;
            resourceInputs["vmid"] = args ? args.vmid : undefined;
            resourceInputs["unuseds"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(LXCContainer.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering LXCContainer resources.
 */
export interface LXCContainerState {
    arch?: pulumi.Input<string>;
    bwlimit?: pulumi.Input<number>;
    clone?: pulumi.Input<string>;
    cloneStorage?: pulumi.Input<string>;
    cmode?: pulumi.Input<string>;
    console?: pulumi.Input<boolean>;
    cores?: pulumi.Input<number>;
    cpulimit?: pulumi.Input<number>;
    cpuunits?: pulumi.Input<number>;
    description?: pulumi.Input<string>;
    features?: pulumi.Input<inputs.LXCContainerFeatures>;
    force?: pulumi.Input<boolean>;
    full?: pulumi.Input<boolean>;
    hagroup?: pulumi.Input<string>;
    hastate?: pulumi.Input<string>;
    hookscript?: pulumi.Input<string>;
    hostname?: pulumi.Input<string>;
    ignoreUnpackErrors?: pulumi.Input<boolean>;
    lock?: pulumi.Input<string>;
    memory?: pulumi.Input<number>;
    mountpoints?: pulumi.Input<pulumi.Input<inputs.LXCContainerMountpoint>[]>;
    nameserver?: pulumi.Input<string>;
    networks?: pulumi.Input<pulumi.Input<inputs.LXCContainerNetwork>[]>;
    onboot?: pulumi.Input<boolean>;
    ostemplate?: pulumi.Input<string>;
    ostype?: pulumi.Input<string>;
    password?: pulumi.Input<string>;
    pool?: pulumi.Input<string>;
    protection?: pulumi.Input<boolean>;
    restore?: pulumi.Input<boolean>;
    rootfs?: pulumi.Input<inputs.LXCContainerRootfs>;
    searchdomain?: pulumi.Input<string>;
    sshPublicKeys?: pulumi.Input<string>;
    start?: pulumi.Input<boolean>;
    startup?: pulumi.Input<string>;
    swap?: pulumi.Input<number>;
    tags?: pulumi.Input<string>;
    targetNode?: pulumi.Input<string>;
    template?: pulumi.Input<boolean>;
    tty?: pulumi.Input<number>;
    unique?: pulumi.Input<boolean>;
    unprivileged?: pulumi.Input<boolean>;
    unuseds?: pulumi.Input<pulumi.Input<string>[]>;
    vmid?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a LXCContainer resource.
 */
export interface LXCContainerArgs {
    arch?: pulumi.Input<string>;
    bwlimit?: pulumi.Input<number>;
    clone?: pulumi.Input<string>;
    cloneStorage?: pulumi.Input<string>;
    cmode?: pulumi.Input<string>;
    console?: pulumi.Input<boolean>;
    cores?: pulumi.Input<number>;
    cpulimit?: pulumi.Input<number>;
    cpuunits?: pulumi.Input<number>;
    description?: pulumi.Input<string>;
    features?: pulumi.Input<inputs.LXCContainerFeatures>;
    force?: pulumi.Input<boolean>;
    full?: pulumi.Input<boolean>;
    hagroup?: pulumi.Input<string>;
    hastate?: pulumi.Input<string>;
    hookscript?: pulumi.Input<string>;
    hostname?: pulumi.Input<string>;
    ignoreUnpackErrors?: pulumi.Input<boolean>;
    lock?: pulumi.Input<string>;
    memory?: pulumi.Input<number>;
    mountpoints?: pulumi.Input<pulumi.Input<inputs.LXCContainerMountpoint>[]>;
    nameserver?: pulumi.Input<string>;
    networks?: pulumi.Input<pulumi.Input<inputs.LXCContainerNetwork>[]>;
    onboot?: pulumi.Input<boolean>;
    ostemplate?: pulumi.Input<string>;
    ostype?: pulumi.Input<string>;
    password?: pulumi.Input<string>;
    pool?: pulumi.Input<string>;
    protection?: pulumi.Input<boolean>;
    restore?: pulumi.Input<boolean>;
    rootfs?: pulumi.Input<inputs.LXCContainerRootfs>;
    searchdomain?: pulumi.Input<string>;
    sshPublicKeys?: pulumi.Input<string>;
    start?: pulumi.Input<boolean>;
    startup?: pulumi.Input<string>;
    swap?: pulumi.Input<number>;
    tags?: pulumi.Input<string>;
    targetNode: pulumi.Input<string>;
    template?: pulumi.Input<boolean>;
    tty?: pulumi.Input<number>;
    unique?: pulumi.Input<boolean>;
    unprivileged?: pulumi.Input<boolean>;
    vmid?: pulumi.Input<number>;
}
